## To edit once for one participant

In [74]:
pt_num = '1'

In [75]:
image_dir = '/Users/ayesh/Desktop/Gradstuff/Temp_mem2022/Scenes_selected/' 
onlyfiles = [f for f in listdir(image_dir) if isfile(join(image_dir, f))]
context_pics = []
for i in onlyfiles:
    stimpath = 'Scenes_selected/' + i
    context_pics.append(stimpath)
    
## OBJECTS
obj_dir = '/Users/ayesh/Desktop/Gradstuff/Temp_mem2022/transpobjects/' 
objfiles = [f for f in listdir(obj_dir) if isfile(join(obj_dir, f))]
obj_pics = []
for i in objfiles:
    stimpath = 'transpobjects/' + i
    obj_pics.append(stimpath)
    
shuffle(context_pics)
shuffle(obj_pics)

## To edit each run

In [242]:
run_num = '5'

In [243]:
## importing all libraries and dependencies
import pandas as pd
import numpy as np
import os
from os import listdir
import glob
from os.path import isfile, join
import shutil
import PIL
from PIL import Image
import random
import math
from heapq import merge
from random import *

In [244]:
from random import *


length = 4
cont = ["S", "T"]
print("\nBismillah!")
s = choice(cont)
s2 = []
while True:
    x = choice(cont)
    if not s2 or s2.count(s[-1] + x) < length:
        print("adding")
        s2.append(s[-1] + x)
        print(s[-1] + x)
        s += x
        print(s2.count(s[-1] + x))
        print(s)
    if len(s2) == length*4: break

pos = randrange(0, len(s2))

print("=-=-=-=-=-=-=-=-=-=-=")
print(pos)
print(len(s2))
print("=-=-=-=-=-=-=-=-=-=-=")

print("\n\n")
print(s)
print(s2)
print(s2.count("SS"),
      s2.count("ST"),
      s2.count("TS"),
      s2.count("TT"),
      len(s),
      len(s2))

s2.insert(pos, "C")
print(s2)

print(s2.count("SS"),
      s2.count("ST"),
      s2.count("TS"),
      s2.count("TT"),
      len(s),
      len(s2))

print("\n\nAlhumdulilaah!")
print("\nOmar solved it! may Allah ease his troubles ameen! sum ameen!")

Bismillah!
adding
TT
1
TT
adding
TS
0
TTS
adding
SS
1
TTSS
adding
ST
1
TTSST
adding
TT
2
TTSSTT
adding
TS
1
TTSSTTS
adding
SS
2
TTSSTTSS
adding
SS
3
TTSSTTSSS
adding
ST
2
TTSSTTSSST
adding
TT
3
TTSSTTSSSTT
adding
TT
4
TTSSTTSSSTTT
adding
TS
3
TTSSTTSSSTTTS
adding
SS
4
TTSSTTSSSTTTSS
adding
ST
4
TTSSTTSSSTTTSST
adding
TS
4
TTSSTTSSSTTTSSTS
adding
ST
4
TTSSTTSSSTTTSSTST
=-=-=-=-=-=-=-=-=-=-=
5
16
=-=-=-=-=-=-=-=-=-=-=



TTSSTTSSSTTTSSTST
['TT', 'TS', 'SS', 'ST', 'TT', 'TS', 'SS', 'SS', 'ST', 'TT', 'TT', 'TS', 'SS', 'ST', 'TS', 'ST']
4 4 4 4 17 16
['TT', 'TS', 'SS', 'ST', 'TT', 'C', 'TS', 'SS', 'SS', 'ST', 'TT', 'TT', 'TS', 'SS', 'ST', 'TS', 'ST']
4 4 4 4 17 17


Alhumdulilaah!

Omar solved it! may Allah ease his troubles ameen! sum ameen!

In [245]:
safec = []
threatc = []
allcs = []
allcnums = []
allctypes = []

for i, a in enumerate(s):
    if a == 'S':
        cnum = i
        ctype = 'SAFE'
        cs = str(cnum) + ctype
        safec.append(cs)
        allcs.append(cs)
        allcnums.append(cnum)
        allctypes.append(ctype)
    if a == 'T':
        cnum = i
        ctype = 'THREAT'
        cs = str(cnum) + ctype
        threatc.append(cs)
        allcs.append(cs)
        allcnums.append(cnum)
        allctypes.append(ctype)

## shock context randomization

In [246]:
rnd1 = pos
print(rnd1)
allcs.insert(pos, "shock-cntxt")
allcnums.insert(pos, "000")
allctypes.insert(pos, "shock")
prior= pos-1
post= pos+1
allcs.insert(post, allcs[prior])
allcnums.insert(post, allcnums[prior])
allctypes.insert(post, allctypes[prior])


# for cntxt in threatc:
#     shckc = allcs[rnd1]
#     print (shckc)
# for smcntxts in allcs:
#     if smcntxts == shckc: 
#         index = allcs.index(smcntxts)
#         allcs[index]= "shock-cntxt"
print (threatc)
print (allcs)

5
['0THREAT', '1THREAT', '4THREAT', '5THREAT', '9THREAT', '10THREAT', '11THREAT', '14THREAT', '16THREAT']
['0THREAT', '1THREAT', '2SAFE', '3SAFE', '4THREAT', 'shock-cntxt', '4THREAT', '5THREAT', '6SAFE', '7SAFE', '8SAFE', '9THREAT', '10THREAT', '11THREAT', '12SAFE', '13SAFE', '14THREAT', '15SAFE', '16THREAT']

In [247]:
len(allcs)

19

In [248]:
len(allcnums)

19

In [249]:
trial_ls = ['1','2','3','4','5','6']
ls = trial_ls * len(allcs)
len(ls)

114

In [250]:
df = pd.DataFrame(
    {'context_num': allcnums,
     'context_type': allctypes})

df.insert(2, "context_shock", pd.Series(['shock-cntxt'], index=[pos]))
df.loc[prior, "context_shock"] = "prior"
df.loc[post, "context_shock"] = "post"
df['context_shock'] = df['context_shock'].astype(str)
df

   context_num context_type context_shock
0            0       THREAT           nan
1            1       THREAT           nan
2            2         SAFE           nan
3            3         SAFE           nan
4            4       THREAT         prior
5          000        shock   shock-cntxt
6            4       THREAT          post
7            5       THREAT           nan
8            6         SAFE           nan
9            7         SAFE           nan
10           8         SAFE           nan
11           9       THREAT           nan
12          10       THREAT           nan
13          11       THREAT           nan
14          12         SAFE           nan
15          13         SAFE           nan
16          14       THREAT           nan
17          15         SAFE           nan
18          16       THREAT           nan

In [251]:
newdf = pd.DataFrame(np.repeat(df.values, 6, axis=0))
newdf.columns = df.columns
newdf['cntxt_trialnum'] = ls
#newdf['shock_bool'] = newdf['shock_bool'].astype(str)
print(newdf)

    context_num context_type context_shock cntxt_trialnum
0             0       THREAT           nan              1
1             0       THREAT           nan              2
2             0       THREAT           nan              3
3             0       THREAT           nan              4
4             0       THREAT           nan              5
..          ...          ...           ...            ...
109          16       THREAT           nan              2
110          16       THREAT           nan              3
111          16       THREAT           nan              4
112          16       THREAT           nan              5
113          16       THREAT           nan              6

[114 rows x 4 columns]

## shock randomization

In [252]:
## radnom assignment of shock frequency, it'll be either once or twice in a shock context
shckfreq= [1,2]
c = choice(shckfreq)

In [253]:
# random assignment of shock after the trial #
shock_objectlist = []
if c == 1:
    shockobj = randint(1,5)
    shock_objectlist.append(shockobj)
elif c == 2:
    shock_objectlist = (sample([1,2,3,4,5], 2))
    
# random assignment of shock during the 2s ITI
shock_time = []
if len(shock_objectlist)==1: 
    rndobj = random()
    shock_time.append(rndobj)
if len(shock_objectlist) ==2:
    rndobj1 = random()
    rndobj2 = random()
    shock_time.append(rndobj1)
    shock_time.append(rndobj2)
    
shock_objectlist = [str(i) for i in shock_objectlist]
shock_objectlist, shock_time

(['2', '4'], [0.30631545324847576, 0.05572738478614181])

In [254]:
shockcntxtobjcts=[]
for index, row in newdf.iterrows():
    if (newdf.context_shock[index]=='shock-cntxt') and (newdf.cntxt_trialnum[index] in shock_objectlist):
        shockcntxtobjcts.append(index)
        
shocks = [1] * len(shock_objectlist)
shocks
newdf.insert(4, "shock_object", pd.Series(shocks, index=shockcntxtobjcts))
newdf['shock_object'] = newdf['shock_object'].astype(str)

newdf.insert(5, "us", pd.Series(shocks, index=shockcntxtobjcts))
newdf['us'] = newdf['us'].astype(str)


newdf.insert(6, "shock_time", pd.Series(shock_time, index=shockcntxtobjcts))
newdf['shock_time'] = newdf['shock_time'].astype(str)
newdf

,context_num,context_type,context_shock,cntxt_trialnum,shock_object,us,shock_time
0,0,THREAT,nan,1,nan,nan,nan
1,0,THREAT,nan,2,nan,nan,nan
2,0,THREAT,nan,3,nan,nan,nan
3,0,THREAT,nan,4,nan,nan,nan
4,0,THREAT,nan,5,nan,nan,nan
...,...,...,...,...,...,...,...
109,16,THREAT,nan,2,nan,nan,nan
110,16,THREAT,nan,3,nan,nan,nan
111,16,THREAT,nan,4,nan,nan,nan
112,16,THREAT,nan,5,nan,nan,nan
113,16,THREAT,nan,6,nan,nan,nan

In [255]:
for index, row in newdf.iterrows():
    if newdf.us[index]=='nan':
        newdf.us[index] = str(0)
        
newdf

,context_num,context_type,context_shock,cntxt_trialnum,shock_object,us,shock_time
0,0,THREAT,nan,1,nan,0,nan
1,0,THREAT,nan,2,nan,0,nan
2,0,THREAT,nan,3,nan,0,nan
3,0,THREAT,nan,4,nan,0,nan
4,0,THREAT,nan,5,nan,0,nan
...,...,...,...,...,...,...,...
109,16,THREAT,nan,2,nan,0,nan
110,16,THREAT,nan,3,nan,0,nan
111,16,THREAT,nan,4,nan,0,nan
112,16,THREAT,nan,5,nan,0,nan
113,16,THREAT,nan,6,nan,0,nan

## stim randomizations

In [256]:
## resize
# image_dir = '/Users/ayesh/Desktop/Gradstuff/Temp_mem2022/Scenes_selected/scenes_newly_added/'
# image_list = os.listdir(image_dir)
# printed_list = []
# for a in image_list:
#     im = Image.open (image_dir + a)
#     a_resized = im.resize((500, 500), Image.ANTIALIAS)
#     a_resized.save(image_dir + a, "JPEG", optimize=True)
#     a_size = a_resized.size, a
#     printed_list.append(a_size)

### TEMPORAL DISTANCE

In [257]:
# ### CONTEXTS
# image_dir = '/Users/ayesh/Desktop/Gradstuff/Temp_mem2022/Scenes_selected/' 
# onlyfiles = [f for f in listdir(image_dir) if isfile(join(image_dir, f))]
# context_pics = []
# for i in onlyfiles:
#     stimpath = 'Scenes_selected/' + i
#     context_pics.append(stimpath)
    
# ## OBJECTS
# obj_dir = '/Users/ayesh/Desktop/Gradstuff/Temp_mem2022/transpobjects/' 
# objfiles = [f for f in listdir(obj_dir) if isfile(join(obj_dir, f))]
# obj_pics = []
# for i in objfiles:
#     stimpath = 'transpobjects/' + i
#     obj_pics.append(stimpath)

In [258]:
# shuffle(context_pics)
# shuffle(obj_pics)
obs1 = []
obs2 = []
obs3 = []
obs4 = []

#runs = [1,2,3,4,5]
#for run in runs:
if run_num == '1':
    contexts = context_pics [0:19]
    objects = obj_pics[0:114]
    obs1.append(objects)
if run_num == '2':
    contexts = context_pics [19:38]
    objects = obj_pics[114:228]
    obs2.append(objects)
if run_num == '3':
    contexts = context_pics [38:57]
    objects = obj_pics[228:342]
    obs3.append(objects)
if run_num == '4':
    contexts = context_pics [57:76]
    objects = obj_pics[342:456]
    obs4.append(objects)
if run_num == '5':
    contexts = context_pics [76:95]
    objects = obj_pics[456:570]

In [259]:
## PT DF
all_contexts = np.repeat(contexts, 6)

newdf['contexts_pics'] = all_contexts
newdf['objects_pics'] = objects

### remove the "shock context" before making the test df
newdf2 = newdf[newdf['context_type'] != 'shock']
newdf2.index = range(len(newdf2))

In [260]:
newdf2

,context_num,context_type,context_shock,cntxt_trialnum,shock_object,us,shock_time,contexts_pics,objects_pics
0,0,THREAT,nan,1,nan,0,nan,Scenes_selected/scene_052.jpg,transpobjects/object179.png
1,0,THREAT,nan,2,nan,0,nan,Scenes_selected/scene_052.jpg,transpobjects/object028.png
2,0,THREAT,nan,3,nan,0,nan,Scenes_selected/scene_052.jpg,transpobjects/2020-03-26(9).png
3,0,THREAT,nan,4,nan,0,nan,Scenes_selected/scene_052.jpg,transpobjects/object017.png
4,0,THREAT,nan,5,nan,0,nan,Scenes_selected/scene_052.jpg,transpobjects/object310.png
...,...,...,...,...,...,...,...,...,...
103,16,THREAT,nan,2,nan,0,nan,Scenes_selected/scene_070.jpg,transpobjects/object236.png
104,16,THREAT,nan,3,nan,0,nan,Scenes_selected/scene_070.jpg,transpobjects/object180.png
105,16,THREAT,nan,4,nan,0,nan,Scenes_selected/scene_070.jpg,transpobjects/object124.png
106,16,THREAT,nan,5,nan,0,nan,Scenes_selected/scene_070.jpg,transpobjects/object145.png
107,16,THREAT,nan,6,nan,0,nan,Scenes_selected/scene_070.jpg,transpobjects/object020.png

In [261]:
### stims to be tested

## WITHIN
within_index = []
within = []
Swithin1 = []
Swithin2 = []
Twithin1 = []
Twithin2 = []

for index, row in newdf2.iterrows():
    ### WITHIN
    if newdf2.cntxt_trialnum[index] == '2' and newdf2.context_type[index] == 'SAFE':
        Swithin1.append(row)
        within.append('within_safe1')
        within_index.append(index)
    if newdf2.cntxt_trialnum[index] == '6' and newdf2.context_type[index] == 'SAFE':
        Swithin2.append(row)
        within.append('within_safe2')
        within_index.append(index)
    if newdf2.cntxt_trialnum[index] == '2' and newdf2.context_type[index] == 'THREAT':
        Twithin1.append(row)
        within.append('within_threat1')
        within_index.append(index)
    if newdf2.cntxt_trialnum[index] == '6' and newdf2.context_type[index] == 'THREAT':
        Twithin2.append(row)
        within.append('within_threat2')
        within_index.append(index)

In [262]:
##ACROSS 
across_index = []
across = []
Sacross1 = []
Sacross2 = []
Tacross1 = []
Tacross2 = []

for index, row in newdf2.iterrows():
    if newdf2.cntxt_trialnum[index] == '5' and newdf2.context_type[index] == 'SAFE' and newdf2.context_num[index]!=16:
        Sacross1.append(row)
        across.append('across_safe1')
        across_index.append(index)
    if newdf2.cntxt_trialnum[index] == '3' and newdf2.context_type[index] == 'SAFE' and newdf2.context_num[index]!=0:
        Sacross2.append(row)
        across.append('across_safe2')
        across_index.append(index)
        
    if newdf2.cntxt_trialnum[index] == '5' and newdf2.context_type[index] == 'THREAT' and newdf2.context_num[index]!=16:
        Tacross1.append(row)
        across.append('across_threat1')
        across_index.append(index)
    if newdf2.cntxt_trialnum[index] == '3' and newdf2.context_type[index] == 'THREAT'and newdf2.context_num[index]!=0:
        Tacross2.append(row)
        across.append('across_threat2')
        across_index.append(index)

In [263]:
all_inds = list(merge(within_index,across_index))
newdf2.insert(8, "condition", pd.Series(within, index=within_index))
for t in newdf2.condition:
    newdf2.condition[across_index] = across

C:\Users\ayesh\Anaconda3\lib\site-packages\pandas\core\series.py:1061: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.loc[key] = value
C:\Users\ayesh\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3418: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  exec(code_obj, self.user_global_ns, self.user_ns)

In [264]:
newdf2

,context_num,context_type,context_shock,cntxt_trialnum,shock_object,us,shock_time,contexts_pics,condition,objects_pics
0,0,THREAT,nan,1,nan,0,nan,Scenes_selected/scene_052.jpg,NaN,transpobjects/object179.png
1,0,THREAT,nan,2,nan,0,nan,Scenes_selected/scene_052.jpg,within_threat1,transpobjects/object028.png
2,0,THREAT,nan,3,nan,0,nan,Scenes_selected/scene_052.jpg,NaN,transpobjects/2020-03-26(9).png
3,0,THREAT,nan,4,nan,0,nan,Scenes_selected/scene_052.jpg,NaN,transpobjects/object017.png
4,0,THREAT,nan,5,nan,0,nan,Scenes_selected/scene_052.jpg,across_threat1,transpobjects/object310.png
...,...,...,...,...,...,...,...,...,...,...
103,16,THREAT,nan,2,nan,0,nan,Scenes_selected/scene_070.jpg,within_threat1,transpobjects/object236.png
104,16,THREAT,nan,3,nan,0,nan,Scenes_selected/scene_070.jpg,across_threat2,transpobjects/object180.png
105,16,THREAT,nan,4,nan,0,nan,Scenes_selected/scene_070.jpg,NaN,transpobjects/object124.png
106,16,THREAT,nan,5,nan,0,nan,Scenes_selected/scene_070.jpg,NaN,transpobjects/object145.png
107,16,THREAT,nan,6,nan,0,nan,Scenes_selected/scene_070.jpg,within_threat2,transpobjects/object020.png

In [265]:
within_1 = newdf2.loc[newdf2['cntxt_trialnum'] == '2']
within_2 = newdf2.loc[newdf2['cntxt_trialnum'] == '6']
across_1 = newdf2.loc[newdf2['cntxt_trialnum'] == '5']
across_2 = newdf2.loc[newdf2['cntxt_trialnum'] == '3']

In [266]:
len(across_1)

18

In [267]:
### test pairs

within_1 = newdf2.loc[newdf2['cntxt_trialnum'] == '2']
within_2 = newdf2.loc[newdf2['cntxt_trialnum'] == '6']
across_1 = newdf2.loc[newdf2['cntxt_trialnum'] == '5']
across_2 = newdf2.loc[newdf2['cntxt_trialnum'] == '3']

across_2 = across_2.drop(across_2[(across_2.context_num == 0)].index)
across_1 = across_1.drop(across_1[(across_1.context_num == 16)].index)

cmbin1 = pd.concat([within_1, across_1], join="inner")
cmbin2 = pd.concat([within_2, across_2], join="inner")

cmbin2 = cmbin2.rename(columns={'context_num': "context_num2", 'context_type':"context_type2", 'context_shock':"context_shock2", 'cntxt_trialnum':"cntxt_trialnum2",
       'shock_object':"shock_object2", 'us':"us2",'shock_time':"shock_time2", 'contexts_pics':"contexts_pics2", 'objects_pics':"objects_pics2",
       'condition': "condition2"})

cmbin1.index = cmbin2.index
testdf = pd.concat([cmbin1, cmbin2], axis=1)

### SOURCE MEMORY TEST

In [268]:
newdf2
## correct context

tst_obj = []
cor_cntxt = []
tst_val = []
all_safe = []
all_threat = []

for index, row in newdf2.iterrows():
    tst_obj.append(newdf2.objects_pics[index])
    cor_cntxt.append(newdf2.contexts_pics[index])
    tst_val.append(newdf2.context_type[index])
    if newdf2.context_type[index] == 'SAFE':
        all_safe.append(newdf2.contexts_pics[index])
    if newdf2.context_type[index] == 'THREAT':
        all_threat.append(newdf2.contexts_pics[index])

In [269]:
## foil contexts
same_foil = []
same_val = []
opp_foil = []
opp_val = []
for index, row in newdf2.iterrows():
    tst = newdf2.contexts_pics[index]
    if tst in all_safe:
        b = [x for x in all_safe if x != tst]
        foil = choice(b)
        foil2 = choice(all_threat)
        same_foil.append(foil)
        opp_foil.append(foil2)
        same_val.append('safe')
        opp_val.append('threat')
    if tst in all_threat:
        b = [x for x in all_threat if x != tst]
        foil = choice(b)
        foil2 = choice(all_safe)
        same_foil.append(foil)
        opp_foil.append(foil2)
        same_val.append('threat')
        opp_val.append('safe')

srcdf = pd.DataFrame(
    {'test_object': tst_obj,
     'correct_context': cor_cntxt,
    'tested_valence': tst_val,
    'same_val': same_val,
    'opp_val': opp_val,
    'same_foil': same_foil,
    'opp_foil': opp_foil})

In [270]:
len(same_foil)

108

## participant csvs

In [271]:
data_folder = 'C:/Users/ayesh/Desktop/Gradstuff/Temp_mem2022/pt_stimfiles/'
pt = "stimfile_%s" %pt_num
path = os.path.join(data_folder, pt)
pt_folder = os.makedirs(path, exist_ok = True)

##make a pt csv
newdf.to_csv(path+"/loop_%s.csv"%run_num, index = False, header = True)
testdf.to_csv(path+"/testloop_%s.csv"%run_num, index = False, header = True)
srcdf.to_csv(path+"/srcloop_%s.csv"%run_num, index = False, header = True)


#pt_list = pd.DataFrame(
   # {'context_num': allcnums,
    # 'context_type': allctypes,
     #'shocktime': shock_time,
     #'shockobjects': shock_objectlist})

In [29]:
#pt_list.to_csv(path+"/edit_test.csv", index = False, header = True)